import Head from "next/head";

import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import {
  useFormik,
  FormikProvider,
  Form,
  useField,
  Field,
  validateYupSchema,
} from "formik";
import * as Yup from "yup";
import axios from "axios";
import { ContactForm } from "../src/components/Form";
import { Widget } from "../src/components/Widget/Widget";
import { Header } from "../src/components/Header";
import { Footer } from "../src/components/Footer";
import { Welcome } from "../src/components/Welcome";
import { Advantages } from "../src/components/Advantages";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const TextInputLiveFeedback = ({ label, helpText, ...props }: any) => {
  const [field, meta] = useField(props);

  // Show inline feedback if EITHER
  // - the input is focused AND value is longer than 2 characters
  // - or, the has been visited (touched === true)
  const [didFocus, setDidFocus] = React.useState(false);
  const handleFocus = () => setDidFocus(true);
  const showFeedback =
    (!!didFocus && field.value.trim().length > 2) || meta.touched;

  return (
    <div
      className={`form-control ${
        showFeedback ? (meta.error ? "invalid" : "valid") : ""
      }`}
    >
      <div className="flex items-center space-between gap-2 ">
        <label htmlFor={props.id}>{label}</label>{" "}
        {showFeedback ? (
          <div
            id={`${props.id}-feedback`}
            aria-live="polite"
            className="feedback text-sm text-red-600"
          >
            {meta.error ? meta.error : <p className="text-green-600">✓</p>}
          </div>
        ) : null}
      </div>
      <input
        {...props}
        {...field}
        aria-describedby={`${props.id}-feedback ${props.id}-help`}
        onFocus={handleFocus}
      />
      <div className="text-xs" id={`${props.id}-help`} tabIndex={-1}>
        {helpText}
      </div>
    </div>
  );
};

function Home() {
  return (
    <div className="relative">
      <Head>
        <title>Fótum Enenharia</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Header />
        <Welcome />
        <Advantages />
        <ContactForm />
        <Footer />
        <Widget />
      </main>
    </div>
  );
}
export default Home;
